#! /bin/bash

arxiv=()
files=()
for file; do
    if [[ $file = http://arxiv.org/pdf/*.pdf ]]; then
        arxiv+=("$file")
    else
        files+=("$file")
    fi
done

LPR="lpr -o sides=two-sided-long-edge"
SSH="ssh atom@143.239.221.57"

if [ ${#arxiv[@]} -gt 0 ]; then
    GET="wget "${arxiv[@]}" --user-agent=Lynx -q --output-document=- | "$LPR""
    CMD="$SSH $GET" 
    $CMD
fi

if [ ${#files[@]} -gt 0 ]; then
    CMD="$SSH $LPR"
    $CMD < "${files[@]}"
fi

