#! /bin/bash

LPR="ssh atom@143.239.221.57 lpr -o sides=two-sided-long-edge"

if [[ $1 = http://arxiv.org/pdf/*.pdf ]]
    then
        wget $1 --user-agent=Lynx -q --output-document=- | $LPR
    else
        $LPR < $1
    fi
