#! /bin/bash

LPR="lpr -o sides=two-sided-long-edge"
SSH="ssh atom@143.239.221.57"
CMD=""

arxiv=()
files=()
for file; do
    if [[ $file = http://arxiv.org/pdf/*.pdf ]]; then
        arxiv+=("$file")
    else
        files+=("$file")
    fi
done

if [ ${#arxiv[@]} -gt 0 ]; then
    TMP="wget "${arxiv[@]}" --user-agent=Lynx -q --output-document=- | "$LPR";"
    CMD="$CMD $TMP" 
fi

if [ ${#files[@]} -gt 0 ]; then
    TMP=""$LPR" < "${files[@]}";"
    CMD="$CMD $TMP"
fi

"$SSH" << EOF
    "$CMD"
EOF
